# resume.py
import torch
import torch.nn.functional as F
import os
import sys
from core.governor import ShannonEntropyGovernor
from core.manifold import RiemannianEmbeddingManifold
from core.immune import GeometricImmunityEngine
from crisis.collapse import HawkingReincarnationEngine
from utils.checkpoint import ManifoldCheckpointManager

def resume_evolutionary_loop(checkpoint_file):
    dimension = 64
    learning_rate = 0.01
    total_steps = 15
    
    # Initialize components
    governor = ShannonEntropyGovernor(h_max=5.95)
    space = RiemannianEmbeddingManifold(dimension=dimension)
    immunity = GeometricImmunityEngine(dimension=dimension, rotational_threshold=1.5)
    reincarnation_pod = HawkingReincarnationEngine(dimension=dimension)
    ckpt_manager = ManifoldCheckpointManager()
    
    print("======================================================================")
    print("RESUMING PROJECT: AI_TRUNG_SINH FROM HISTORICAL PERSISTENT STATE")
    print("======================================================================")
    
    try:
        # Hydrate the tensor weights from the state file
        snapshot = ckpt_manager.load_generational_state(checkpoint_file)
        
        # Inject the historical values back into the live components
        current_generation = snapshot["generation"]
        starting_step = snapshot["step"]
        
        with torch.no_grad():
            space.weights.copy_(snapshot["manifold_weights"])
            reincarnation_pod.core_seed.copy_(snapshot["core_knowledge_seed"])
            space.g.copy_(snapshot["metric_tensor_g"])
            
        print(f" -> Successfully re-anchored at Generation {current_generation}, Step {starting_step}")
        print(" -> All Riemannian geometries, core seeds, and metric fields hydrated.")
    except Exception as e:
        print(f"[RESUME ERROR] Critical failure during tensor hydration: {e}")
        return

    # Advance the cycle tracker and continue running the simulation pass
    next_generation = current_generation + 1
    print(f"\n--- COMMENCING MANIFOLD TRACKING FOR RESUMED GENERATION {next_generation} ---")
    
    for step in range(1, total_steps + 1):
        if step > 12:
            print(" -> [CRITICAL INFUSION] Injecting absolute maximum uniform noise (Total Structural Chaos)...")
            data_stream = torch.randn(dimension) * 0.001
        else:
            noise_factor = step * 0.5
            data_stream = torch.randn(dimension) + noise_factor
        
        norm_data_stream = F.normalize(data_stream, p=2, dim=0)
        target_vector = F.normalize(torch.randn(dimension), p=2, dim=0)
        
        current_h = governor.compute_entropy(data_stream)
        L_H, R_H, V_H, collapse_triggered = governor.get_triadic_scale(current_h, data_stream)
        
        print(f"[Resumed Gen {next_generation} | Step {step:02d}] Entropy: {current_h:.4f} | Core: {L_H*100:.1f}%, Vaccine: {R_H*100:.1f}%")
        
        is_route_safe = immunity.evaluate_cauchy_bound(norm_data_stream, target_vector, space.g)
        if not is_route_safe:
            continue
            
        space.update_metric_field(scalar_curvature_factor=R_H)
        mock_flat_gradient = torch.randn(dimension, dimension) * 0.05
        space.project_tangent_step(mock_flat_gradient, lr=learning_rate)
        
        if collapse_triggered:
            pure_knowledge_seed = reincarnation_pod.execute_collapse_and_emit(space, space.weights)
            with torch.no_grad():
                space.weights.copy_(space.manifold.projx(pure_knowledge_seed))
                
            ckpt_manager.save_generational_state(
                generation=next_generation,
                step=step,
                weights=space.weights,
                core_seed=reincarnation_pod.core_seed,
                metric_g=space.g
            )
            print(f"System successfully re-initialized into Generation {next_generation + 1} from inherited genes.")
            break

if __name__ == "__main__":
    # Target the specific checkpoint file generated by your main.py run
    target_checkpoint = "ai_trung_sinh_gen_1_step_13.pt"
    resume_evolutionary_loop(target_checkpoint)
